services:
  - type: web
    name: career-copilot-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=$PORT --server.enableCORS=false
    pythonVersion: 3.10.13
